### ISSUE TITLE
Why does this library exist?

### ISSUE THREAD

**Issue by MasterEric** [akursat/react-leaflet-cluster#1]
[react-leaflet-markercluster](https://www.npmjs.com/package/react-leaflet-markercluster) already has widespread adoption and an active repository that includes a 3.0.0-rc1 release for react-leaflet v3 support.

Why not modify the existing library to include TypeScript support and create a pull request?

**Comment by akursat** [comment]
@MasterEric The existing library contains some issues like performance problems etc. Because of that, I've thought it's was inactive. I'm planning to create another library for react-leaflet. This repository is a preparation for that library.

**Comment by MasterEric** [comment]
Okay, that makes sense to me.
