### ISSUE TITLE
Support React Leaflet v4 and Leaflet v1.8?

### ISSUE THREAD

**Issue by falkoschumann** [akursat/react-leaflet-cluster#11]
There is an update to React Leaflet with support for Leaflet v1.8 and React v18. Is it possible to use React Leaflet Cluster with it? The peer dependency to React v17, prevents installation with NPM.

Leaflet v1.8 solves some problems with current iOS versions.

**Comment by scottnimos** [comment]
I created a fork and updated the dependencies. https://www.npmjs.com/package/react-leaflet-markercluster-v2
However, I could only get it working by passing in a custom icon (L.Icon) on the Markers

**Comment by 217013462** [comment]
> I created a fork and updated the dependencies. https://www.npmjs.com/package/react-leaflet-markercluster-v2 However, I could only get it working by passing in a custom icon (L.Icon) on the Markers

I tried to use the mentioned NPM (v2) but nothing shows up. Here is the error code shown in console.
![image](https://user-images.githubusercontent.com/101268150/172110263-70e219d7-b442-4ddc-b2af-d1d23e52e522.png)

"dependencies": {
    "leaflet": "1.8.0",
    "leaflet.markercluster": "1.5.3",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-leaflet": "4.0.0",
    "react-leaflet-markercluster-v2": "1.0.4",
    "react-router-dom": "6.3.0"
}

Any idea how to solve this? Thanks!

**Comment by akursat** [comment]
@falkoschumann You can use v1.3.0 to use get leaflet v.1.8.0
@217013462 @scottnimos Please check out the v2.0.0 to react-leaflet v4 support.
