### ISSUE TITLE
A Faster Version even though with a bad clustering algorithm 

### ISSUE THREAD

**Issue by sahin52** [akursat/react-leaflet-cluster#14]
I am not sure if the problem is with React or the algorithm but the app crashes (or becomes very slow) with 50K+ objects. Can you explain if the problem is with React. Or can you develop a stupid version of clustering if the problem is with the algorithm

**Comment by akursat** [comment]
@sahin52 There are a couple ways to solve performance issues. For example, show only the markers on the map that are in the boundary of your view. Your question is not related to this package so I'm closing the issue.
