### ISSUE TITLE
Hooks order error with react-leaflet 4 when re-rendering

### ISSUE THREAD

**Issue by jacobweberbowery** [akursat/react-leaflet-cluster#15]
* Open the [Custom marker cluster](https://codesandbox.io/s/beautiful-pike-j2l0w?file=/src/App.tsx) example from the home page.
* Go to the Sandbox Info tab and update react-leaflet to the latest, 4.0.2.
* Change one of the markers so it re-renders, e.g. change the string "a title".
* A hooks order error appears:
```
Warning: React has detected a change in the order of Hooks called by ForwardRef(ContainerComponent). This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. useRef                     useRef
3. useEffect                  useRef
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at ContainerComponent (https://j2l0w.csb.app/node_modules/@react-leaflet/core/lib/component.js:15:52)
    at div
    at MapContainerComponent (https://j2l0w.csb.app/node_modules/react-leaflet/lib/MapContainer.js:49:21)
    at div
    at App 
    in ContainerComponent (created by App)
    in App
```

(I've also seen this locally with the latest version of create-react-app and its dependencies, React 1.8, and Leaflet 1.8.0.)

**Comment by lhs1478** [comment]
Hello, I also have this problem. Have you found a solution? Can you share it if it is convenient?

**Comment by jacobweberbowery** [comment]
@lhs1478

> Hello, I also have this problem. Have you found a solution? Can you share it if it is convenient?

Only downgrading react to 17.x and react-leaflet to 3.x.

**Comment by lhs1478** [comment]
Ok, thank you.

**Comment by Santehnikua** [comment]
Got same problems after update from react-leaflet 4.0.1 to react-leaflet 4.0.2
With 4.0.1 everything was working well. BUT! If i downgrade package back - it still not working. 
So i need to edit packages-lock file and change @react-leaflet/core from 2.0.1 to 2.0.0
After this i got this working again.

Hope this help to find and fix the problem

**Comment by grayds** [comment]
Whew, thought I might be the only one with this issue.

The steps above didn't do it for me, so I'll just have to work on preventing re-renders, or perhaps forcing a remount, as workarounds until a fix is discovered.

**Comment by moranbw** [comment]
@akursat Is the ability to update just not implemented? Let us know if there's anything we can do to help.

https://github.com/akursat/react-leaflet-cluster/blob/5277510c8ebeba44dae28285011771c8902a7cba/src/index.tsx#L70-L78

**Comment by kylemorena** [comment]
> Whew, thought I might be the only one with this issue.
> 
> The steps above didn't do it for me, so I'll just have to work on preventing re-renders, or perhaps forcing a remount, as workarounds until a fix is discovered.

Hi @moranbw, 
I think the problem is here https://github.com/akursat/react-leaflet-cluster/blob/5277510c8ebeba44dae28285011771c8902a7cba/src/index.tsx#L51-L62 
I still haven't found a solution.

**Comment by moranbw** [comment]
FWIW, I worked around this for the time-being by just forcing a re-render of the cluster like this:

```
            <MarkerClusterGroup
                iconCreateFunction={createClusterCustomIcon}
                maxClusterRadius={40}
                key={uuidv4()}
                removeOutsideVisibleBounds={false}
            >
```

I don't have too much data on my map...just a couple hundred Points...so I have not noticed an impact on performance.  This may not be the case for 1k-10ks of Points...

**Comment by moranbw** [comment]
> > 
> 
> Forcing a render means that you load tiles twice, is not a good deal...

This only forces a re-render of the the Cluster whenever something has changed with my feature layer (like the underlying data via filters).

This has nothing to do with Tile Layers...

**Comment by yurihnrq** [comment]
> FWIW, I worked around this for the time-being by just forcing a re-render of the cluster like this:
> 
> ```
> <MarkerClusterGroup
>     iconCreateFunction={createClusterCustomIcon}
>     maxClusterRadius={40}
>     key={uuidv4()}
>     removeOutsideVisibleBounds={false}
> >
> ```
> 
> I don't have too much data on my map...just a couple hundred Points...so I have not noticed an impact on performance. This may not be the case for 1k-10ks of Points...

@moranbw your solution solved my problem, thanks. Waiting for a definitive fix.

**Comment by nicholasskupien** [comment]
This solution works... but I have other things causing re-renders so I am getting stuck in infinite render loops.

Does anyone have any other ideas? Or maybe they have tried another clustering library/wrapper that supports re-rendering?

**Comment by akursat** [comment]
@nickskupien @yurihnrq @moranbw @kylemorena @grayds @Santehnikua @jacobweberbowery @lhs1478 The addressed problem should be gone with the new version. Please give it a try and let me know if you still encounter a problem.

**Comment by akursat** [comment]
Please see updated example to rerender a marker. https://codesandbox.io/s/beautiful-pike-j2l0w?file=/src/App.tsx

**Comment by moranbw** [comment]
hey @akursat -- thanks for the fix and great package.

It does indeed work for me without error.  It does seem a bit slower when re-rendering, compared to when I was providing a `key` as explained above.  But this is just my perception, I have not done any deep render analysis on it yet.
