### ISSUE TITLE
iconCreateFunction is call for each child Marker

### ISSUE THREAD

**Issue by Barruchou** [akursat/react-leaflet-cluster#16]
Hello,

Unlike your demo, on my side the "iconCreateFunction" method is called for each "Marker" child. This is not efficient at all. More exactly it is when the component re-renders.
In your demo there is only one cluster and "iconCreateFunction" is only called once, then called again when zooming.
In my code I only have one cluster but "iconCreateFunction" is called 6 times (Marker count).
Can you try on your side by causing a new render and see if it does the same?

Thanks in advance

**Comment by akursat** [comment]
@Barruchou Memorize your function before pass to the MarkerCluster component.
