### ISSUE TITLE
GPL License restricts use by closed-source projects.

### ISSUE THREAD

**Issue by MasterEric** [akursat/react-leaflet-cluster#2]
As @tirli mentioned in [this comment](https://github.com/yuzhva/react-leaflet-markercluster/issues/133#issuecomment-796750613), this project uses the GPLv3 license. This is notable in it stipulates that any software which uses this library cannot be closed source, and thus this library cannot be used in closed-source projects.

This is compared to the react-leaflet-markercluster, which utilizes the MIT License.

Is this distinction intentional?

**Comment by akursat** [comment]
Hi @MasterEric, I moved the license of the project to MIT. My hobby projects are mostly GPL licensed. Because of this habit, I licensed this project as GPL. This library will use the MIT license from now on.Thank you for your interest. 
https://www.npmjs.com/package/react-leaflet-cluster/v/1.0.3

**Comment by MasterEric** [comment]
@tril Letting you know about this.

**Comment by tirli** [comment]
@MasterEric, I've got the notification. Thank you :)
(considering that you tried to mention me in the message above)
