### ISSUE TITLE
Cannot use lib in NextJS

### ISSUE THREAD

**Issue by benbenpetit** [akursat/react-leaflet-cluster#21]
Hello,

Thank you for this library, I am trying to use it with NextJS but I have troubles making it work.
NextJS doesn't let me use the library because CSS cannot be imported within your lib. See error below

```
./node_modules/react-leaflet-cluster/lib/assets/MarkerCluster.Default.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/react-leaflet-cluster/lib/index.js
```

**Comment by jackbuscombe** [comment]
add this line to your next.config.mjs:
`transpilePackages: ["react-leaflet-cluster"]`
