### ISSUE TITLE
Vite - import external css  

### ISSUE THREAD

**Issue by raphaelcunha** [akursat/react-leaflet-cluster#25]
When running the server using [vite](https://vitejs.dev/) the error below is dispatched.

<img width="1535" alt="Screenshot 2023-03-10 at 08 49 39" src="https://user-images.githubusercontent.com/3853552/224308721-9ecc8e5b-4ba2-446c-a45c-1d2961ee325e.png">

To solve this: 

[index.tsx
](https://github.com/akursat/react-leaflet-cluster/blob/main/src/index.tsx)
```
require("./assets/MarkerCluster.css?inline");
require("./assets/MarkerCluster.Default.css?inline");

```
Make sense to add this ?inline suffix?

**Comment by akursat** [comment]
@raphaelcunha I didn't find any errors with Vite. I'll publish an example using Vite.

**Comment by akursat** [comment]
@raphaelcunha  Please see https://github.com/akursat/react-leaflet-cluster/tree/main/examples/vite-example
