### ISSUE TITLE
Popup remove event triggered twice before actually opening the popup

### ISSUE THREAD

**Issue by ndevplanque** [akursat/react-leaflet-cluster#27]
Hello, thank you for the great work over this package.

The bug is, the very first time I click on a popup, the handlePopupClose function is fired two times before actually opening the popup. It is then properly fired when closing the popup.
The problem stops after the first popup.

```
import MarkerClusterGroup from 'react-leaflet-cluster'

<MarkerClusterGroup>
  <Marker>
    <Popup eventHandlers={{ remove: handlePopupClose }}>
      // ...
    </Popup>
  </Marker>
</MarkerClusterGroup>
```

`leaflet 1.9.3`
`leaflet.markercluster 1.5.3`
`react 18.2.0`
`react-leaflet 4.2.1`
`react-leaflet-cluster 2.1.0`

The bug disappear when I delete `<MarkerClusterGroup>`

Do you know any workaround to this problem ?
Any idea how you can patch this ?

Again thanks for the great work with this package

**Comment by akursat** [comment]
@ndevplanque Could you create a sandbox demo for me?
