### ISSUE TITLE
[New feature] Make iconCreateFunction react to changes

### ISSUE THREAD

**Issue by pedrodcsousa** [akursat/react-leaflet-cluster#3]
Hey,
Thank you for your work in this library!
Currently migrating from [react-leaflet-markercluster](https://github.com/yuzhva/react-leaflet-markercluster) and really enjoying the prospect of this new lib.

However, I came across a feature that would be awesome to have.
More details below.

**Objective:**
Like the `Marker`'s `customIcon` function, find a way to easily change the properties of the clusterCustomIcon
(maybe with an implementation of [refreshing clusters)](https://github.com/Leaflet/Leaflet.markercluster#refreshing-the-clusters-icon)

**Current solution** (find example below):
- save each clusters reference
- trigger the change on useEffect, by accessing the cluster ref

**Problems with this solution**:
- not feasible if we have a lot of clusters and just want to highlight one cluster, based on its children
- example: click a button to change the cluster that has "Marker X"

**Example**:
- click the highlight button to change the border of the icons
- works well with customIcon for the Marker (runs on re-render)
- does not work for iconCreateFunction in MarkerClusterGroup (its only called once)

https://codesandbox.io/s/elegant-bohr-zzi05?file=/src/App.tsx

**Comment by akursat** [comment]
Hi @pedrodcsousa, Did you tried to pass a ref to MarkerClusterGroup and call clusterRef.current.refreshClusters() function? If this doesn't work I will try to fix the problem as soon as possible.
