### ISSUE TITLE
Can't show popup inside cluster

### ISSUE THREAD

**Issue by dinhthanhtai** [akursat/react-leaflet-cluster#35]
- I have an issue that can't show pop-up inside the cluster, how can I resolve it?

**Comment by leprigabriel** [comment]
I have the same issue. In my case, i am using react-leaflet to render polygons in my map. Popup component works fine when used with Marker component, and the issue is hapenning only for GeoJSON component.
@dinhthanhtai did you find a way to fix it?

**Comment by akursat** [comment]
@dinhthanhtai Please create a sandbox demo and open issue again.

**Comment by kodobrody** [comment]
I have similar issue, but my case is a bit more complicated I think.
My case is that some markers will overlap, so at max zoom they are still clustered. Clicking on them will spiderfy them (which is fine) and clicking on marker then will show popup just fine, however I would like to programatically spiderfy the cluster and then show the popup, based on the marker data eg id. Would that be possible?
