### ISSUE TITLE
iconUrl not set in Icon options (see the docs).

### ISSUE THREAD

**Issue by vyemialyanchyk** [akursat/react-leaflet-cluster#5]
![image](https://user-images.githubusercontent.com/642868/121970311-ef579580-cd7e-11eb-9468-10bf77f2dfc9.png)

▼ 32 stack frames were expanded.
NewClass._createIcon
https://nrd3e.csb.app/node_modules/leaflet/dist/leaflet-src.js:7084:13
NewClass.createIcon
https://nrd3e.csb.app/node_modules/leaflet/dist/leaflet-src.js:7070:17
NewClass._initIcon
https://nrd3e.csb.app/node_modules/leaflet/dist/leaflet-src.js:7548:29
NewClass.onAdd
https://nrd3e.csb.app/node_modules/leaflet/dist/leaflet-src.js:7455:10

**Comment by jspc** [comment]
I'm also seeing this. @vyemialyanchyk  - did you figure out how to get past this?

**Comment by vyemialyanchyk** [comment]
I just did not use this raw library, waiting for stable workable for my circumstances version...

**Comment by akursat** [comment]
@vyemialyanchyk @jspc I've updated the example. Please check again.
