### ISSUE TITLE
Global CSS cannot be imported from within node_modules (next js)

### ISSUE THREAD

**Issue by junjou** [akursat/react-leaflet-cluster#6]
Hello, 

Seems like it can't work with nextjs:

![image](https://user-images.githubusercontent.com/36960251/128481945-8054eb97-be40-4727-993e-72d342d6f886.png)

**Comment by akursat** [comment]
@junjou The maintainers of nextjs decided to allow CSS imports from node_modules. I hope the error will be gone. I'll follow the PR and test it when it is merged.

**Comment by koeit** [comment]
Is this still not fixed @akursat or any workaround?

**Comment by akursat** [comment]
@koeit Please follow the discussion https://github.com/vercel/next.js/discussions/27953 [possible workaround](https://github.com/vercel/next.js/discussions/27953#discussioncomment-2606542)

**Comment by rosnaib11** [comment]
+ 1

**Comment by SublimeProphets** [comment]
upvote! :-)

**Comment by StrangersSoftware** [comment]
Does anyone found some solution? Can you share the code if "yes"?

**Comment by r1skz3ro** [comment]
@StrangersSoftware use this library - https://github.com/bem/next-global-css

adjust your `next.config.js` like in the snippet below, restart the project and it should work :)

```
  const { patchWebpackConfig } = require('next-global-css');
  const webpackNodeExternals = require('webpack-node-externals');
  
  const nextConfig = {
    {...}
    webpack: (config, options) => {
      patchWebpackConfig(config, options);
      if (options.isServer) {
        config.externals = webpackNodeExternals({
          allowlist: [/design-system/],
        });
      }
      return config;
    },
    {...}
  };
```

**Comment by akursat** [comment]
@junjou @r1skz3ro @StrangersSoftware @SublimeProphets @bsor-dev @koeit The addressed problem should be gone with the new version. Please give it a try and let me know if you still encounter a problem.

**Comment by StrangerTwo** [comment]
@akursat Currently using the version 2.1.0 and still facing this issue.

`error - ../node_modules/react-leaflet-cluster/lib/assets/MarkerCluster.Default.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: ../node_modules/react-leaflet-cluster/lib/index.js`

Let me know if I can help you provide any other information.

**Comment by StrangerTwo** [comment]
I believe the file https://github.com/akursat/react-leaflet-cluster/blob/main/src/index.tsx should not import 

```
import 'leaflet.markercluster/dist/MarkerCluster.css'
import 'leaflet.markercluster/dist/MarkerCluster.Default.css
```

nor

```
import './assets/MarkerCluster.css'
import './assets/MarkerCluster.Default.css'
```

And instead the documentation of 'react-leaflet-cluster' should be changed, so that people import these css files themselves.

Let me know your thoughts! Thanks

**Comment by StrangersSoftware** [comment]
> @junjou @r1skz3ro @StrangersSoftware @SublimeProphets @bsor-dev @koeit The addressed problem should be gone with the new version. Please give it a try and let me know if you still encounter a problem.

The new version still gives me the same error on Next.js.

I solved this by using your index.tsx file as one of my components and added all styles in my projects global css-file.
All the necessary dependencies respectively too.

Thanks for your plugin!

**Comment by jackbuscombe** [comment]
Add this to the next.config.js file:
`transpilePackages: ["react-leaflet-cluster"],`

**Comment by jakobskrym** [comment]
> Add this to the next.config.js file: `transpilePackages: ["react-leaflet-cluster"],`

This worked for me 👍

**Comment by luiskurihara** [comment]
> Add this to the next.config.js file: `transpilePackages: ["react-leaflet-cluster"],`

When i try this, are showing this:

![Captura de tela 2024-07-24 192137](https://github.com/user-attachments/assets/7ed6d489-555f-4314-a8ea-4c6fd3f49f55)

**Comment by yewyewXD** [comment]
> transpilePackages: ["react-leaflet-cluster"],

Add this to the next.config.js file:
`experimental: { esmExternals: 'loose' },`

and make sure you use dynamic import for the component with leaflet inside
```jsx
import dynamic from 'next/dynamic'
const MapApp = dynamic(() => import('@/components/ReactLeafletMap'), { ssr: false })
```
