### ISSUE TITLE
TypeScript types are not imported

### ISSUE THREAD

**Issue by Dorious** [akursat/react-leaflet-cluster#8]
Dunno is it actually your issue, but declaration for `leaftlet.markercluster` is not "merged" and I don't see types.

**Comment by akursat** [comment]
@Dorious could you check example https://codesandbox.io/s/beautiful-pike-j2l0w?file=/src/App.tsx.

**Comment by Dorious** [comment]
Oddly it started to do that after some reinstall on whole node_modules. Thanks.
