### ISSUE TITLE
[Question] Custom dynamic react component as custom cluster for iconCreateFunction prop

### ISSUE THREAD

**Issue by jaballogian** [akursat/react-leaflet-cluster#9]
Hello, I saw here https://codesandbox.io/s/beautiful-pike-j2l0w that you created the custom cluster UI using the `iconCreateFunction` prop and `createClusterCustomIcon` function that returns `L.divIcon` function.

```javascript
<MarkerClusterGroup iconCreateFunction={createClusterCustomIcon}>

...

const createClusterCustomIcon = function (cluster: MarkerCluster) {
  return L.divIcon({
    html: `<span>${cluster.getChildCount()}</span>`,
    className: 'custom-marker-cluster',
    iconSize: L.point(33, 33, true),
  })
}
```

It's the same with the code from another library here https://github.com/YUzhva/react-leaflet-markercluster.

```
const createClusterCustomIcon = function (cluster) {
  return L.divIcon({
    html: `<span>${cluster.getChildCount()}</span>`,
    className: 'marker-cluster-custom',
    iconSize: L.point(40, 40, true),
  });
}

...

<MarkerClusterGroup iconCreateFunction={createClusterCustomIcon} />
```

My question is does your library support using custom dynamic component for example pie chart component for the cluster icon?

I had a problem implementing it here https://stackoverflow.com/questions/71522257/useeffect-hook-isnt-triggered-inside-reactdomserver-rendertostring

**Comment by akursat** [comment]
@jaballogian Did you try to generate html with ReactDOMServer.renderToString?
